---
title: "Chapter 2 - New Take"
author: "Allyson Hamilton"
date: "2022-08-24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import required libraries
# import required libraries
require(tidyverse) # for data formatting
require(ggplot2) 
require(ggpubr) # for plotting
require(lme4)
require(lmerTest) # for mixed-models and GLMMs
require(emmeans) 
require(multcompView)
require(multcomp)# for post-hoc analysis
require(gdata) # contains keep()
require(writexl)
require(ggtext)
require(GGally)
require(VGAM)
```
```{r}
#import the data ----
setwd("~/All School Stuff/All Graduate School/Research/Thesis - Food Inks/Data/Phase 2")

extrusion <- read.table(file = "Phase 2 - Transfer During Extrusion inoc (1).txt",
                     header = TRUE,
                     sep = "\t")
#remove extra columns
extrusion <- extrusion[,-c(1:3,7:9,13:17,23)]

extrusion$soil <- factor(extrusion$soil, levels = c("A", "B" , "P" , "S" ))
extrusion$cap_print <- factor(extrusion$cap_print)
extrusion$microbe <- factor(extrusion$microbe)
```
```{r}
summary(extrusion)
```
```{r}
#extrusion_no_both

extrusion_cap_print  <- droplevels(extrusion[!extrusion$cap_print == "both",])
extrusion_print  <- droplevels(extrusion_cap_print[!extrusion_cap_print$cap_print == "cap",])
```

```{r}
raw_chapter_2 <- ggplot(extrusion_cap_print, aes(x = soil, y = CFU_recovered, shape = cap_print, color = microbe)) + 
  geom_point(position = position_dodge2(0.1), size = 3) +
  ggtitle("") +
  #ylim(0,5) + 
  xlab("Soil Component") +
  ylab("CFU Recovered") + 
  labs(color = "Microorganism:") +
  #scale_color_hue(labels = c("Listeria monocytogenes", "Salmonella Typhimurium")) +
  scale_shape(labels = c("capsule", "print")) +
  labs(shape = "Capsule or Printed Element:")+
  #scale_y_continuous(limits = c(0,10), expand = expand_scale(mult = c(0,0)))+
  theme(plot.title = element_text(hjust = 0.5, face = "plain"),
        panel.background = element_rect(fill="white", color="grey15"),
        strip.background = element_rect(fill=NA),
        strip.text = element_text(face = "italic", size = 13),
        axis.title = element_text(size=13),
        axis.text = element_text(size=12, color="grey35"),
        panel.grid.major.y = element_line(color="grey45", linetype="solid", size=.5),
        #panel.grid.minor.y = element_line(color="grey45", linetype="solid", size=0.25),
        legend.title = element_text(size=13),
        axis.text.y = element_text(color= "black"),
        axis.text.x = element_text(color= "black")) 

ggsave(filename = "Raw_Chapter_2_Data.jpg", width=7, height=5.5, unit="in", plot = raw_chapter_2, path = "C:/Users/allys/Documents/All School Stuff/All Graduate School/Research/Thesis - Food Inks/Data/plots/")
```
```{r}

anova.res <- lm(CFU_recovered ~ microbe*soil*cap_print
                -microbe:soil:cap_print
                -microbe:soil
                -soil:cap_print
                -microbe:cap_print,
                data = extrusion_cap_print)

# display anova table in the console
anova(anova.res)
summary(anova.res)

# residual analysis

plot(anova.res, which = 1) 
plot(anova.res, which = 2)

#horribly non-normal, going to move to analyzing using GLM
```

#```{r}
#post-hoc analysis (not allowed because model isn't linear)
require(emmeans)
require(multcomp)

lsmeans3 <- emmeans(anova.res, specs = ~microbe:soil:cap_print, level = 0.05)
lsmeans3 <- cld(lsmeans3, alpha = 0.05, Letters = letters, decreasing = T)
lsmeans3 <- data.frame(lsmeans3)

# remove excess spaces in .group
lsmeans3$.group <- gsub(" ", "", lsmeans3$.group)
lsmeans3
```
#```{r}
ggplot(data = lsmeans3, aes(x=soil, y=emmean, fill=cap_print))+
  geom_bar(stat="identity", position = position_dodge(), color="black", width=1)+
  geom_errorbar(aes(ymin = lower.CL, ymax =upper.CL), position = position_dodge(width=1))+
   facet_grid(~case_when(microbe == "ST" ~ "*S*. Typhimurium",
                       microbe == "LM" ~ "*L. monocytogenes*")) +
  geom_text(aes(label=.group, y = emmean+10000000), position = position_dodge(width=1), size=2)+
  xlab("Soil Type") + 
  ylab("Estimated CFU Recovered")+
  ggtitle("")+
  #ylim(0, 3E8) +
  scale_fill_manual(values=c("#0072B2", "#56B4E9"), name = "Capsule or Print:", labels = (c("Capsule" , "Print")))+
   theme(panel.background = element_rect(fill=NA, color="grey15"),
              panel.grid.major.x =  element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.y = element_line(color="azure3",linetype="dotted"),
              legend.position = "right",
              axis.text = element_text(size=14, color="grey15"),
              axis.title = element_text(size=12, color="black"),
              legend.title = element_text(size=14),
              legend.text = element_text(size=14),
              plot.title = element_text(size=14, face="bold"),
              axis.text.x = element_text(color = "black", face = "plain", size = 10),
              axis.text.y = element_text(color= "black", size = 10),
              strip.background = element_rect(fill=NA),
              strip.text = ggtext::element_markdown(size = 12))

```

```{r}
glm.quasipoisson <- glm(CFU_recovered ~ microbe*soil*cap_print
                        -microbe:soil:cap_print
                        -microbe:cap_print
                        -microbe:soil, family = quasipoisson(link = "log"), data=extrusion_cap_print)
summary(glm.quasipoisson)
```
```{r}
# post-hoc analysis
glm.quasipoisson.res <- emmeans(glm.quasipoisson, ~ microbe*soil*cap_print, level=0.95)
glm.quasipoisson.res <- cld(glm.quasipoisson.res, alpha = 0.05, Letters = letters, decreasing = TRUE)
glm.quasipoisson.res <- data.frame(glm.quasipoisson.res)
glm.quasipoisson.res 

# Convert log values of estimate, asump.LCL, and asymp.UCL in number of plants
glm.quasipoisson.res$estimate <- exp(glm.quasipoisson.res$emmean)
glm.quasipoisson.res$LCL <- exp(glm.quasipoisson.res$asymp.LCL)
glm.quasipoisson.res$UCL <- exp(glm.quasipoisson.res$asymp.UCL)

# remove excess spaces in .group
glm.quasipoisson.res$.group <- gsub(" ", "", glm.quasipoisson.res$.group)
glm.quasipoisson.res
```

```{r}
# plot results
Chapter_2_quasipoisson <-ggplot(data = glm.quasipoisson.res, aes(x=soil, y=estimate, fill=cap_print))+
  geom_bar(stat="identity", position = position_dodge(width=0.7), color="black", width=0.6)+
  geom_errorbar(aes(ymin = LCL, ymax = UCL), position = position_dodge(width=0.7), width=0.2)+
  geom_text(aes(y = UCL+15000000, label=.group), position = position_dodge(width=0.7), size=3)+
  xlab("Soil Type") + ylab("Estimated CFU Recovered")+
  ggtitle("")+
   facet_grid(~case_when(microbe == "ST" ~ "*S*. Typhimurium",
                     microbe == "LM" ~ "*L. monocytogenes*")) +
  #scale_y_continuous(limits=c(0,12), breaks=seq(0,12,by=2), expand = expand_scale(mult = c(0,0)))+
  scale_fill_manual(values=c("lightgray", "#56B4E9", "#0072B2"), name = "Capsule or Printed Product:", labels = (c("Capsule" , "Print")))+
  theme(panel.background = element_rect(fill=NA, color="grey15"),
           panel.grid.major.x =  element_blank(),
           panel.grid.minor.x = element_blank(),
           panel.grid.major.y = element_line(color="azure3",linetype="dotted"),
           legend.position = "right",
           axis.text = element_text(size=14, color="grey15"),
           axis.title = element_text(size=12, color="black"),
           legend.title = element_text(size=14),
           legend.text = element_text(size=14),
           plot.title = element_text(size=14, face="bold"),
           axis.text.x = element_text(color = "black", face = "plain", size = 10),
           axis.text.y = element_text(color= "black", size = 10),
           strip.background = element_rect(fill=NA),
           strip.text = ggtext::element_markdown(size = 12))

ggsave(filename = "Chapter_2_Quasipoisson.jpg", width=7, height=5.5, unit="in", plot = Chapter_2_quasipoisson, path = "C:/Users/allys/Documents/All School Stuff/All Graduate School/Research/Thesis - Food Inks/Data/plots/")
```