---
title: "Machine Hygiene 4-30"
author: "Allyson Hamilton"
date: "4/30/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# import required libraries
require(tidyverse) # for data formatting
require(ggplot2) 
require(ggpubr) # for plotting
require(lme4)
require(lmerTest) # for mixed-models and GLMMs
require(emmeans) 
require(multcompView)
require(multcomp)# for post-hoc analysis
require(gdata) # contains keep()
```
```{r}
#import the data ----
setwd("~/All School Stuff/All Graduate School/Research/Thesis - Food Inks/Data")

hygiene <- read.table(file = "Phase 1 - Machine Hygiene (5).txt",
                     header = TRUE,
                     sep = "\t")

#remove extra columns
hygiene <- hygiene[,-c(3,6,8:13,15:18,21,24:27)]

#subset only washed treatments
all_hygiene <- hygiene[!is.na(hygiene$wash_type), ]

```
```{r}

#order the legend

all_hygiene$soil <- factor(all_hygiene$soil, levels = c("F", "A", "B" , "P" , "S" ))


all_hygiene$soil <- recode_factor(all_hygiene$soil, F = "unsoiled", A = "mixture", B = "butter" , P = "protein" , S = "sugar")

```
```{r}
#dot plot

all_hygiene_april_30 <- ggplot(all_hygiene, aes(x = log_CFU_on_cap, y = log_reduction_limit, color = wash_type, shape = soil)) +   
  geom_point(position = position_dodge2(0.07), size = 3) + 
  scale_shape_manual(values = c(1, 2, 3, 4 ,7)) + 
  ylim(0,10) + 
  xlab("Log CFU on Capsule") +
  ylab("Log Reduction") + 
  labs(color = "Wash Type") +
  labs(shape = "Soil Level")+
  scale_y_continuous(limits = c(0,10), expand = expand_scale(mult = c(0,0)))+
  facet_grid(~case_when(microbe == "ST" ~ "S. Typhimurium",
                       microbe == "LM" ~ "L. monocytogenes"))+ 
  theme(plot.title = element_text(hjust = 0.5, face = "plain"),
        panel.background = element_rect(fill="white", color="grey15"),
        strip.background = element_rect(fill=NA),
        strip.text = element_text(face = "italic", size = 13),
        axis.title = element_text(size=13),
        axis.text = element_text(size=12, color="grey35"),
        panel.grid.major.y = element_line(color="grey45", linetype="solid", size=.5),
        #panel.grid.minor.y = element_line(color="grey45", linetype="solid", size=0.25),
        legend.title = element_text(size=13),
        axis.text.y = element_text(color= "black"),
        axis.text.x = element_text(color= "black")) 

ggsave(filename = "all_hygiene_april_30.pdf", width=7, height=5.5, unit="in", plot = all_hygiene_april_30)

```
```{r}
all_hygiene_april_30_boxplot <- ggplot(all_hygiene, aes(x = soil, y = log_reduction_limit, color = wash_type)) +   
  geom_boxplot() + 
  ylim(0,10) + 
  xlab("Soil Type") +
  ylab("Log Reduction") + 
  labs(color = "Wash Type") +
  facet_grid(~case_when(microbe == "ST" ~ "S. Typhimurium",
                       microbe == "LM" ~ "L. monocytogenes")) +
  scale_y_continuous(limits = c(0,10), expand = expand_scale(mult = c(0,0)))+
  theme(plot.title = element_text(hjust = 0.5, face = "plain"),
        panel.background = element_rect(fill="white", color="grey15"),
        strip.background = element_rect(fill=NA),
        strip.text = element_text(face = "italic", size = 13),
        axis.title = element_text(size=13),
        axis.text = element_text(size=12, color="grey35"),
        panel.grid.major.y = element_line(color="grey45", linetype="solid", size=.5),
        #panel.grid.minor.y = element_line(color="grey45", linetype="solid", size=0.25),
        legend.title = element_text(size=13),
        axis.text.x = element_text(angle=45,size = 10, vjust = 0.7, color = "black"),
        axis.text.y = element_text(color= "black"))

ggsave(filename = "all_hygiene_april_30_boxplot.pdf", width=7, height=5.5, unit="in", plot = all_hygiene_april_30_boxplot)
```

```{r}
#let's start some stats!!!!
glm.quasipoisson <- glm(log_reduction_limit ~ wash_type * soil, family = quasipoisson(link = "log"), data=all_hygiene)
summary(glm.quasipoisson)
```

```{r}
# post-hoc analysis
glm.quasipoisson.res <- emmeans(glm.quasipoisson, ~ wash_type:soil, level=0.95)
glm.quasipoisson.res <- cld(glm.quasipoisson.res, alpha = 0.05, Letters = letters, decreasing = TRUE)
glm.quasipoisson.res <- data.frame(glm.quasipoisson.res)
glm.quasipoisson.res 

# Convert log values of estimate, asump.LCL, and asymp.UCL in number of plants
glm.quasipoisson.res$estimate <- exp(glm.quasipoisson.res$emmean)
glm.quasipoisson.res$LCL <- exp(glm.quasipoisson.res$asymp.LCL)
glm.quasipoisson.res$UCL <- exp(glm.quasipoisson.res$asymp.UCL)

# remove excess spaces in .group
glm.quasipoisson.res$.group <- gsub(" ", "", glm.quasipoisson.res$.group)
glm.quasipoisson.res
```
```{r}
# plot results
glm.quasipoisson.plot <- ggplot(data = glm.quasipoisson.res, aes(x=soil, y=estimate, fill=wash_type))+
  geom_bar(stat="identity", position = position_dodge(width=0.7), color="black", width=0.6)+
  geom_errorbar(aes(ymin = LCL, ymax = UCL), position = position_dodge(width=0.7), width=0.2)+
  geom_text(aes(y = UCL+0.5, label=.group), position = position_dodge(width=0.7), size=4)+
  xlab("") + ylab("Estimated Log Reduction")+
  ggtitle("GLM with Quasipoisson Errors")+
  scale_y_continuous(limits=c(0,12), breaks=seq(0,12,by=2), expand = expand_scale(mult = c(0,0)))+
  scale_fill_manual(values=c("#000000", "#56B4E9", "#0072B2"), name = "Wash Type:")+
  theme(panel.background = element_rect(fill=NA, color="grey15"),
              panel.grid.major.x =  element_blank(),
              panel.grid.minor.x = element_blank(),
              panel.grid.major.y = element_line(color="grey15",linetype="dotted"),
              legend.position = "right",
              axis.text = element_text(size=14, color="grey15"),
              axis.title = element_text(size=16, color="black"),
              legend.title = element_text(size=16),
              legend.text = element_text(size=16),
              plot.title = element_text(size=16, face="bold"),
              axis.text.x = element_text(color = "black", face = "plain", size = 12),
              axis.text.y = element_text(color= "black", size = 12),
              axis.title.y = element_text(size = 12))
glm.quasipoisson.plot

ggsave(filename = "GLM with quasipoisson errors.pdf", width=7, height=5.5, unit="in", plot = glm.quasipoisson.plot)


```


